// Code generated by 'malatd gen' command.
// The temporary code used to ensure successful compilation!
// When the project is completed, it should be removed!

package logic

import (
	"daywork/xl/k8Demo/args"
	td "github.com/swxctx/malatd"
)

// Ping handler
func V1_Test_Ping(ctx *td.Context, arg *args.PingArgsV1) (*args.PingResultV1, *td.Rerror) {
	return &args.PingResultV1{
		Text: "hello k8s.",
	}, nil
}
