// Code generated by 'malatd gen' command.
// DO NOT EDIT!

package api

import (
	td "github.com/swxctx/malatd"
	"github.com/swxctx/malatd/binding"

	"daywork/xl/k8Demo/args"
	"daywork/xl/k8Demo/logic"
)

// Ping handler
func PingHandle(ctx *td.Context) {
	// bind arg
	arg := new(args.PingArgsV1)
	if err := binding.Binder(ctx, arg); err != nil {
		ctx.RenderRerr(td.RerrInternalServer.SetReason(err.Error()))
		return
	}

	// api logic
	result, rerr := logic.V1_Test_Ping(ctx, arg)
	if rerr != nil {
		ctx.RenderRerr(rerr)
		return
	}
	ctx.Render(result)
}
